Models/CommentProduct.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommentProduct()
        {
            this.CommentProduct1 = new HashSet<CommentProduct>();
        }
    
        public int ID { get; set; }
        public string Content { get; set; }
        public int ProductID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Reply_coment { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentProduct> CommentProduct1 { get; set; }
        public virtual CommentProduct CommentProduct2 { get; set; }
    }
}

Controllers/CommentProductsController.cs
using GardenShopOnline.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace GardenShopOnline.Controllers
{
    public class CommentProductsController : Controller
    {
        private readonly BonsaiGardenEntities db = new BonsaiGardenEntities();

        // GET: CommentProducts
        [CustomAuthorize(Roles = "Admin, Staff")]
        public ActionResult Index()
        {

            var commentProducts = db.CommentProducts.Include(c => c.Product);
            return View(commentProducts.ToList());
        }
        public ActionResult CommentProduct(int product_id)
        {
            var commentProducts = db.CommentProducts.Include(c => c.Product).Where(c => c.ProductID == product_id && c.Status == 2);
            return PartialView(commentProducts.ToList());
        }
        [CustomAuthorize(Roles = "Admin, Staff")]
        public ActionResult CommentProductList()
        {
            var commentProducts = db.CommentProducts.Include(c => c.Product);
            return PartialView(commentProducts.ToList());
        }
        [CustomAuthorize(Roles = "Admin, Staff")]
        public ActionResult EditStatus_Comment(CommentProduct cmt)
        {
            CommentProduct comment = db.CommentProducts.Find(cmt.ID);
            if (cmt.Status == 2)
            {
                comment.Status = 2;

            }
            else if (cmt.Status == 3)
            {
                comment.Status = 3;

            }
            db.Entry(comment).State = EntityState.Modified;
            db.SaveChanges();
            return Json("EditStatus_Order", JsonRequestBehavior.AllowGet);
        }
        [CustomAuthorize(Roles = "Admin, Staff")]
        public ActionResult ReplyComment(CommentProduct cmt)
        {
            CommentProduct comment = new CommentProduct();
            comment.Content = cmt.Content;
            comment.ProductID = cmt.ProductID;
            comment.DateCreated = DateTime.Now;
            comment.UserID = User.Identity.GetUserId();
            comment.Reply_coment = cmt.Reply_coment;
            comment.Status = 2;
            db.CommentProducts.Add(comment);
            db.SaveChanges();
            CommentProduct commentProduct = db.CommentProducts.Find(cmt.Reply_coment);
            commentProduct.Status = 2;
            db.Entry(commentProduct).State = EntityState.Modified;
            db.SaveChanges();
            return Json("ReplyComment", JsonRequestBehavior.AllowGet);
        }
        [CustomAuthorize(Roles = "Admin, Staff")]
        // GET: CommentProducts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CommentProduct commentProduct = db.CommentProducts.Find(id);
            if (commentProduct == null)
            {
                return HttpNotFound();
            }
            return View(commentProduct);
        }

        // GET: CommentProducts/Create
        public ActionResult Create()
        {
            ViewBag.ProductID = new SelectList(db.Products, "ID", "Name");
            return View();
        }

        // POST: CommentProducts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Content,AccManagerID,Answer,ProductID,AccCustomerID,DateCreated,Approval")] CommentProduct commentProduct)
        {
            if (ModelState.IsValid)
            {
                db.CommentProducts.Add(commentProduct);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProductID = new SelectList(db.Products, "ID", "Name", commentProduct.ProductID);
            return View(commentProduct);
        }

        // GET: CommentProducts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CommentProduct commentProduct = db.CommentProducts.Find(id);
            if (commentProduct == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProductID = new SelectList(db.Products, "ID", "Name", commentProduct.ProductID);
            return View(commentProduct);
        }

        // POST: CommentProducts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Content,AccManagerID,Answer,ProductID,AccCustomerID,DateCreated,Approval")] CommentProduct commentProduct)
        {
            if (ModelState.IsValid)
            {
                db.Entry(commentProduct).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProductID = new SelectList(db.Products, "ID", "Name", commentProduct.ProductID);
            return View(commentProduct);
        }

        // GET: CommentProducts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CommentProduct commentProduct = db.CommentProducts.Find(id);
            if (commentProduct == null)
            {
                return HttpNotFound();
            }
            return View(commentProduct);
        }

        // POST: CommentProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CommentProduct commentProduct = db.CommentProducts.Find(id);
            db.CommentProducts.Remove(commentProduct);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/CommentProducts/CommentProduct.cshtml
@model IEnumerable<GardenShopOnline.Models.CommentProduct>

<div class="blog-comment mt-0">
    <h4 class="heading">Comments (@Model.Count())</h4>
    @foreach (var item in Model.Where(c => c.Reply_coment == null))
    {
        <div class="blog-comment-item">
            <div class="blog-comment-img">
                <img src="~/assets/customer/images/blog/avatar/1-1-120x120.png" alt="User Image">
            </div>
            <div class="blog-comment-content">
                <div class="user-meta">
                    <h2 class="user-name">@item.AspNetUser.Email</h2>
                    <span class="date">@item.DateCreated</span>
                </div>
                <p class="user-comment">
                    @item.Content
                </p>
            </div>
        </div>
        var Replycoment = item.CommentProduct1.ToList();
        if (Replycoment != null && Replycoment.Count() > 0)
        {
            foreach (var item1 in Replycoment)
            {
                <div class="blog-comment-item relpy-item">
                    <div class="blog-comment-img">
                        <img src="~/assets/customer/images/blog/avatar/1-1-120x120.png" alt="User Image">
                    </div>
                    <div class="blog-comment-content">
                        <div class="user-meta">
                            <h2 class="user-name">@item1.AspNetUser.Email</h2>
                            <span class="date">@item1.DateCreated</span>
                        </div>
                        <p class="user-comment">
                            @item1.Content
                        </p>
                      
                    </div>
                </div>
            }
        }
    }

</div>

Views/CommentProducts/CommentProductList.cshtml
@model IEnumerable<GardenShopOnline.Models.CommentProduct>
@{
    int no1 = 0;
    int no2 = 0;
    int no3 = 0;

}
<input hidden type="text" id="URDEditStatus_Comment" value="@Url.Action("EditStatus_Comment", "CommentProducts")">
<input hidden type="text" id="URDReplyComment" value="@Url.Action("ReplyComment", "CommentProducts")">


<div class="card-body">
    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="pills-create-tab" data-toggle="pill" href="#pills-create" role="tab" aria-controls="pills-create" aria-selected="true">New</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " id="pills-confirm-tab" data-toggle="pill" href="#pills-confirm" role="tab" aria-controls="pills-confirm" aria-selected="false">Approved</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " id="pills-sent-tab" data-toggle="pill" href="#pills-sent" role="tab" aria-controls="pills-sent" aria-selected="false">Refused</a>
        </li>

    </ul>

    <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade active show" id="pills-create" role="tabpanel" aria-labelledby="pills-create-tab">
            <div class="card">
                <div class="card-body table-border-style">

                    <div class="table-responsive">
                        <table id="example" class="table table-hover ">
                            <thead>
                                <tr>
                                    <th class="text-center ">#</th>
                                    <th class="">Name product</th>
                                    <th class="">Email</th>
                                    <th class="">Content</th>
                                    <th class="text-center">Date created</th>
                                    <th class="text-center"></th>

                                </tr>

                            </thead>
                            <tbody>
                                @foreach (var item in Model.Where(m => m.Status == 1))
                                {
                                    no1++;
                                    <tr>
                                        <td>@no1</td>
                                        <td>
                                            <a href="@Url.Action("Details","Products", new { id = item.ProductID })">@item.Product.Name</a>
                                        </td>
                                        <td>@item.AspNetUser.UserName</td>
                                        <td>@item.Content</td>
                                        <td>@item.DateCreated</td>
                                        <td class="text-center">
                                            <button title="Reply" class="btn btn-info" onclick="GetCmt('@item.ID', '@item.ProductID')">
                                                <i class="feather icon-server">
                                                </i>
                                            </button>
                                            <button title="chấp nhận" class="btn btn-success" onclick="EditStatus_comment('@item.ID', 2)">
                                                <i class="feather icon-check">
                                                </i>
                                            </button>

                                            <button title="từ chối" class="btn btn-danger " onclick="EditStatus_comment('@item.ID', 3)">
                                                <i class="feather icon-trash-2">
                                                </i>
                                            </button>

                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>




                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade  " id="pills-confirm" role="tabpanel" aria-labelledby="pills-confirm-tab">
            <div class="card">
                <div class="card-body table-border-style">
                    <div class="table-responsive">
                        <table id="example1" class="table table-hover ">
                            <thead>
                                <tr>
                                    <th class="text-center ">#</th>
                                    <th class="">Name product</th>
                                    <th class="">Email</th>
                                    <th class="">Content</th>
                                    <th class="text-center">Date created</th>

                                </tr>

                            </thead>
                            <tbody>
                                @foreach (var item in Model.Where(m => m.Status == 2))
                                {
                                    no2++;
                                    <tr>
                                        <td>@no2</td>
                                        <td><a href="@Url.Action("Details","Products", new { id = item.ProductID })">@item.Product.Name</a></td>
                                        <td>@item.AspNetUser.UserName</td>
                                        <td>@item.Content</td>
                                        <td>@item.DateCreated</td>

                                    </tr>
                                }
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>

        </div>
        <div class="tab-pane fade " id="pills-sent" role="tabpanel" aria-labelledby="pills-sent-tab">
            <div class="card">
                <div class="card-body table-border-style">
                    <div class="table-responsive">
                        <table id="example2" class="table table-hover ">
                            <thead>
                                <tr>
                                    <th class="text-center ">#</th>
                                    <th class="">Name product</th>
                                    <th class="">Email</th>
                                    <th class="">Content</th>
                                    <th class="text-center">Date created</th>

                                </tr>

                            </thead>
                            <tbody>
                                @foreach (var item in Model.Where(m => m.Status == 3))
                                {
                                    no3++;
                                    <tr>
                                        <td>@no3</td>
                                        <td><a href="@Url.Action("Details","Products", new { id = item.ProductID })">@item.Product.Name</a></td>
                                        <td>@item.AspNetUser.UserName</td>
                                        <td>@item.Content</td>
                                        <td>@item.DateCreated</td>

                                    </tr>
                                }
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<div id="ReplyComment" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="ReplyCommentLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form class="needs-validation" novalidate>
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    <h5 class="modal-title" id="AddCategoryLabel">Reply</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>

                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>
                                    Reply<span class="text-danger">*</span>
                                </label>
                                <input hidden id="edit_idComment" />
                                <input hidden id="edit_idProduct" />

                                <div class="position-relative">
                                    <textarea placeholder="Enter reason for order cancellation!" id="replyComment" class="form-control" name="reason" rows="4"></textarea>

                                </div> <!---->
                            </div>
                        </div>
                    </div>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn  btn-secondary" data-dismiss="modal">Hủy</button>
                    <button type="button" class="btn btn-primary" onclick="Reply_comment()">lưu</button>
                </div>
            </div>
        </form>
    </div>
</div>

Views/CommentProducts/Create.cshtml
@model GardenShopOnline.Models.CommentProduct

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CommentProduct</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccManagerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccManagerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccManagerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductID, "ProductID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccCustomerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccCustomerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccCustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Approval, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Approval)
                    @Html.ValidationMessageFor(model => model.Approval, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/CommentProducts/Delete.cshtml
@model GardenShopOnline.Models.CommentProduct

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CommentProduct</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccManagerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccManagerID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Answer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Answer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccCustomerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccCustomerID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Approval)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Approval)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/CommentProducts/Details.cshtml
@model GardenShopOnline.Models.CommentProduct

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>CommentProduct</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccManagerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccManagerID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Answer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Answer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccCustomerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccCustomerID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Approval)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Approval)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/CommentProducts/Index.cshtml
@model IEnumerable<GardenShopOnline.Models.CommentProduct>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="pcoded-main-container">
    <div class="pcoded-content">
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Tồn kho</h5>
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="https://tancool.net">
                                    <i class="feather icon-home">
                                    </i>
                                </a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="javascript:void(0)">Tồn kho</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card" id="dataContainer">
                        @{ Html.RenderAction("CommentProductList", "CommentProducts");}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section scripts {
    <script type="text/javascript">
        var row;
        $(document).ready(function () {
            $('#example').DataTable({
                pagingType: 'full_numbers',
            });
            $('#example1').DataTable({
                pagingType: 'full_numbers',
            });
            $('#example2').DataTable({
                pagingType: 'full_numbers',
            });

        });
        //----------------------FILTER ORDER DATE TIME------------------------------------------------

        function GetList_comment() {
            $.ajax({
                url: '@Url.Action("CommentProductList", "CommentProducts")',
                data: {},
            }).done(function (result) {
                $('#dataContainer').html(result);
                $('#example').DataTable();
                $('#example1').DataTable();
                $('#example2').DataTable();


            }).fail(function (XMLHttpRequest, textStatus, errorThrown) {
                console.log(textStatus)
                console.log(errorThrown)
                alert("Something Went Wrong, Try Later");
            });
        }


    </script>
}