Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GardenShopOnline.Models
{
    public partial class ShoppingCart
    {
        readonly BonsaiGardenEntities db = new BonsaiGardenEntities();
        string ShoppingCartId { get; set; }
        public const string CartSessionKey = "CartId";
        public static ShoppingCart GetCart(HttpContextBase context)
        {
            var cart = new ShoppingCart();
            cart.ShoppingCartId = cart.GetCartId(context);

            return cart;
        }

        // Helper method to simplify shopping cart calls
        public static ShoppingCart GetCart(Controller controller)
        {
            return GetCart(controller.HttpContext);
        }

        public void AddToCart(Product product, int? quantity)
        {
            // Get the matching cart and product instances
            var cartItem = db.Carts.SingleOrDefault(
                c => c.ID == ShoppingCartId
                && c.ProductID == product.ID);

            if (cartItem == null)
            {
                // Create a new cart item if no cart item exists
                cartItem = new Cart
                {
                    ProductID = product.ID,
                    ID = ShoppingCartId,
                    Count = quantity == null ? 1 : (int)quantity,
                    Subtotal = product.Price
                };
                db.Carts.Add(cartItem);
            }
            else
            {
                // If the item does exist in the cart, 
                // then add one to the quantity
                cartItem.Count = quantity == null ? cartItem.Count + 1 : cartItem.Count + (int)quantity;
                cartItem.Subtotal = product.Price * cartItem.Count;
            }
            // Save changes
            db.SaveChanges();
        }

        public int DecreaseQuantity(int id)
        {
            // Get the cart
            var cartItem = db.Carts.Single(
                cart => cart.ID == ShoppingCartId
                && cart.RecordID == id);

            int itemCount = 0;

            if (cartItem != null)
            {
                if (cartItem.Count > 1)
                {
                    cartItem.Count--;
                    cartItem.Subtotal = cartItem.Product.Price * cartItem.Count;
                    itemCount = (int)cartItem.Count;
                }
                else
                {
                    db.Carts.Remove(cartItem);
                }
                // Save changes
                db.SaveChanges();
            }
            return itemCount;
        }

        public int RemoveProduct(int id)
        {
            // Get the cart
            var cartItem = db.Carts.Where(
                cart => cart.ID == ShoppingCartId
                && cart.RecordID == id);

            int itemCount = 0;

            if (cartItem != null)
            {
                itemCount = GetCount();
                db.Carts.RemoveRange(cartItem);
                // Save changes
                db.SaveChanges();
            }
            return itemCount;
        }

        public void EmptyCart()
        {
            var cartItems = db.Carts.Where(
                cart => cart.ID == ShoppingCartId);

            foreach (var cartItem in cartItems)
            {
                db.Carts.Remove(cartItem);
            }
            // Save changes
            db.SaveChanges();
        }

        public List<Cart> GetCartItems()
        {
            return db.Carts.Where(
                cart => cart.ID == ShoppingCartId).ToList();
        }
        public int GetCount()
        {
            // Get the count of each item in the cart and sum them up
            int? count = (from cartItems in db.Carts
                          where cartItems.ID == ShoppingCartId
                          select (int?)cartItems.Count).Sum();
            // Return 0 if all entries are null
            return count ?? 0;
        }

        public decimal GetItemTotal(int id)
        {
            // Get the matching cart and product instances
            var cartItem = db.Carts.SingleOrDefault(
                c => c.ID == ShoppingCartId
                && c.ProductID == id);

            // Get item total
            var total = decimal.Zero;
            if (cartItem != null)
            {
                total = cartItem.Subtotal;
            }
            return total;
        }

        public decimal GetTotal()
        {
            // Multiply product price by count of that product to get 
            // the current price for each of those products in the cart
            // sum all product price totals to get the cart total
            decimal? total = (from cartItems in db.Carts
                              where cartItems.ID == ShoppingCartId
                              select (int?)cartItems.Subtotal).Sum();

            return total ?? decimal.Zero;
        }

        public string CreateOrder(CustomerOrder order)
        {
            var cartItems = GetCartItems();
            string quality_product = "";
            bool flat = false;
            // Iterate over the items in the cart, 
            // adding the order details for each
            foreach (var item in cartItems)
            {
                var product = db.Products.Find(item.ProductID);

                var orderDetail = new OrderDetail
                {
                    ProductID = item.ProductID,
                    OrderID = order.ID,
                    UnitPrice = item.Product.Price,
                    Quantity = item.Count
                };
                db.OrderDetails.Add(orderDetail);
                //Subtract the number of products
                product.Quantity -= item.Count;
                db.Entry(product).State = EntityState.Modified;
                if (product.Quantity < 10)
                {
                    flat = true;
                    var requestContext = HttpContext.Current.Request.RequestContext;
                    string link = new UrlHelper(requestContext).Action("Edit", "Products", new { id = product.ID }, HttpContext.Current.Request.Url.Scheme);
                    quality_product += "item <a href='" + link + "'>" + product.Name + "</a> has less than 10 products left, ";
                }
            }

            // Save the order
            db.SaveChanges();
            quality_product += " please check the item again and update the number if necessary.";
            // Empty the shopping cart
            EmptyCart();



            // Return the OrderId as the confirmation number
            if (flat == true)
            {
                return quality_product;
            }
            else
            {
                return "";
            }

        }
        // Check product quantity and order quantity
        public string CheckOrder()
        {
            var cartItems = GetCartItems();
            // Iterate over the items in the cart, 
            // Adding the order details for each
            string error = string.Empty;
            bool flat = false;
            foreach (var item in cartItems)
            {
                //Check product quantity
                var product = db.Products.Find(item.ProductID);
                if (product.Quantity < item.Count)
                {
                    flat = true;
                    error += " " + product.Name + " only have " + product.Quantity + "  items left." + "\r\n";
                }
            }
            error += " Please check again!";
            if (flat == true)
            {
                return error;
            }
            else
            {
                return string.Empty;
            }
        }

        // We're using HttpContextBase to allow access to cookies.
        public string GetCartId(HttpContextBase context)
        {
            if (context.Session[CartSessionKey] == null)
            {
                if (!string.IsNullOrWhiteSpace(context.User.Identity.Name))
                {
                    context.Session[CartSessionKey] =
                        context.User.Identity.Name;
                }
                else
                {
                    // Generate a new random GUID using System.Guid class
                    Guid tempCartId = Guid.NewGuid();
                    // Send tempCartId back to client as a cookie
                    context.Session[CartSessionKey] = tempCartId.ToString();
                }
            }
            return context.Session[CartSessionKey].ToString();
        }

        // When a user has logged in, migrate their shopping cart to
        // be associated with their username
        public void MigrateCart(string userName)
        {
            var shoppingCart = db.Carts.Where(
                c => c.ID == ShoppingCartId);

            foreach (Cart item in shoppingCart)
            {
                item.ID = userName;
            }
            db.SaveChanges();
        }
    }
}

Models/ShoppingCartViewModels.cs
using System.Collections.Generic;

namespace GardenShopOnline.Models
{
    public class ShoppingCartViewModels
    {
        public List<Cart> CartItems { get; set; }
        public decimal CartTotal { get; set; }
    }
}

Controllers/ShoppingCartController.cs
using GardenShopOnline.Models;
using System.Linq;
using System.Web.Mvc;

namespace GardenShopOnline.Controllers
{
    public class ShoppingCartController : Controller
    {
        readonly BonsaiGardenEntities db = new BonsaiGardenEntities();

        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModels
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }

        //
        // GET: /ShoppingCart/GetMiniCart
        public ActionResult GetMiniCart()
        {
            var cart = ShoppingCart.GetCart(HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModels
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return PartialView("_MiniCart", viewModel);
        }

        //
        // GET: /ShoppingCart/GetCheckoutCart
        public ActionResult GetCheckoutCart()
        {
            var cart = ShoppingCart.GetCart(HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModels
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return PartialView("_Checkout", viewModel);
        }

        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id, int? quantity)
        {
            // Retrieve the product from the database
            var addedproduct = db.Products
                .Single(product => product.ID == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(HttpContext);
            cart.AddToCart(addedproduct, quantity);

            // Get item subtotal
            var itemTotal = cart.GetItemTotal(addedproduct.ID);

            var results = new ShoppingCartRemoveViewModels
            {
                ItemTotal = itemTotal,
                CartTotal = cart.GetTotal()
            };
            return Json(results, JsonRequestBehavior.AllowGet);
        }

        //
        // AJAX: /ShoppingCart/DecreaseQuantity/5
        [HttpPost]
        public ActionResult DecreaseQuantity(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(HttpContext);

            // Get the name of the product to display confirmation
            var product = db.Carts
                .Single(item => item.RecordID == id).Product;

            // Remove from cart
            int itemCount = cart.DecreaseQuantity(id);
            var itemTotal = cart.GetItemTotal(product.ID);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModels
            {
                Message = product.Name + " has been removed from cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                ItemTotal = itemTotal,
                DecreaseId = id
            };
            return Json(results);
        }

        //
        // AJAX: /ShoppingCart/RemoveProduct/5
        [HttpPost]
        public ActionResult RemoveProduct(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(HttpContext);

            // Get the name of the product to display confirmation
            var product = db.Carts
                .Single(item => item.RecordID == id).Product;

            // Remove from cart
            int itemCount = cart.RemoveProduct(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModels
            {
                Message = product.Name + " has been removed from cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }

        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public int CartSummary()
        {
            var cart = ShoppingCart.GetCart(HttpContext);
            return cart.GetCount();
        }
    }
}

Views/ShoppingCart/Index.cshtml
@model GardenShopOnline.Models.ShoppingCartViewModels

@{
    ViewBag.Title = "Shopping Cart";
}

<!-- Begin Main Content Area -->
<main class="main-content">
    <div class="breadcrumb-area breadcrumb-height" data-bg-image="../../assets/customer/images/breadcrumb/bg/1-1-1919x388.jpg">
        <div class="container h-100">
            <div class="row h-100">
                <div class="col-lg-12">
                    <div class="breadcrumb-item">
                        <h2 class="breadcrumb-heading">Cart Page</h2>
                        <ul>
                            <li>
                                <a href="index.html">Home</a>
                            </li>
                            <li>Cart Page</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="cart-area section-space-y-axis-100">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-success d-none" id="update-message" role="alert"></div>
                    <form action="javascript:void(0)">
                        <div class="table-content table-responsive">
                            <table class="table" id="tblCart">
                                <thead>
                                    <tr>
                                        <th width="10%">remove</th>
                                        <th width="20%">images</th>
                                        <th width="10%">Product</th>
                                        <th width="20%">Unit Price</th>
                                        <th width="20%">Quantity</th>
                                        <th width="20%">Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.CartItems)
                                    {
                                        <tr id="row-@item.RecordID">
                                            <td class="product_remove" data-id="@item.RecordID">
                                                <a href="#">
                                                    <i class="pe-7s-close" data-tippy="Remove" data-tippy-inertia="true"
                                                       data-tippy-animation="shift-away" data-tippy-delay="50"
                                                       data-tippy-arrow="true" data-tippy-theme="sharpborder"></i>
                                                </a>
                                            </td>
                                            <td class="product-thumbnail">
                                                <a href="#">
                                                    <img class="w-25" src="~/assets/images/@item.Product.Image" alt="Cart Thumbnail">
                                                </a>
                                            </td>
                                            <td class="product-name"><a href="@Url.Action("Details", "Products", new { id = item.ProductID })">@item.Product.Name</a></td>
                                            <td class="product-price"><span class="amount">@item.Product.Price.ToString("N0") ₫</span></td>
                                            <td class="quantity" id="item-count-@item.RecordID">
                                                <div class="cart-plus-minus" data-id="@item.RecordID" data-productid="@item.ProductID">
                                                    <input class="cart-plus-minus-box" id="cartItemQuantity" readonly value="@item.Count" type="text">
                                                    <div class="dec qtybutton">
                                                        <i class="fa fa-minus"></i>
                                                    </div>
                                                    <div class="inc qtybutton">
                                                        <i class="fa fa-plus"></i>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="product-subtotal"><span class="amount" id="product-subtotal-@item.ProductID">@item.Subtotal.ToString("N0") ₫</span></td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="coupon-all">
                                    <div class="coupon">
                                        <input id="coupon_code" class="input-text" name="coupon_code" value="" placeholder="Coupon code" type="text">
                                        <input class="button mt-xxs-30" name="apply_coupon" value="Apply coupon" type="submit">
                                    </div>
                                    <div class="coupon2">
                                        <input class="button" name="update_cart" value="Update cart" type="submit">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-5 ml-auto">
                                <div class="cart-page-total">
                                    <h2>Cart totals</h2>
                                    <ul>
                                        <li>Subtotal <span class="cart-total">@Model.CartTotal.ToString("N0") ₫</span></li>
                                        <li>Total <span class="cart-total">@Model.CartTotal.ToString("N0") ₫</span></li>
                                    </ul>
                                    <a href="@Url.Action("AddressAndPayment", "Checkout")">Proceed to checkout</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
<!-- Main Content Area End Here -->

@section scripts{
    <script type="text/javascript">
        $(function () {
            // Document.ready -> link up remove event handler
            $('.product_remove').click(function (e) {
                e.preventDefault();
                // Get the id from the link
                var recordToDelete = $(this).attr('data-id');
                if (recordToDelete != '') {
                    // Perform the ajax post
                    $.post('/ShoppingCart/RemoveProduct', { 'id': recordToDelete }, function (data) {
                        // Successful requests get here
                        // Update the page elements
                        $('#row-' + data.DeleteId).fadeOut('slow');
                        $('.cart-total').text(numberWithDots(data.CartTotal) + ' ₫');
                        $('#update-message').removeClass('d-none').text(data.Message);
                        getMiniCart();
                    });
                }
            });

            $('.quantity .inc').click(function () {
                // Get the id from the link
                var productId = $(this).parent().attr('data-productid');
                if (productId != '') {
                    // Perform the ajax post
                    $.get('/ShoppingCart/AddToCart', { 'id': productId }, function (data) {
                        // Successful requests get here
                        // Update the page elements
                        updateTotal(data, productId);
                        getMiniCart();
                    });
                }
            });

            $('.quantity .dec').click(function () {
                // Get the id from the link
                var recordToDecrease = $(this).parent().attr('data-id');
                var productId = $(this).parent().attr('data-productid');
                var itemQuantity = $('#item-count-' + recordToDecrease).find('input');
                if (recordToDecrease != '' && itemQuantity.val() > 1) {
                    // Perform the ajax post
                    $.post('/ShoppingCart/DecreaseQuantity', { 'id': recordToDecrease }, function (data) {
                        // Successful requests get here
                        itemQuantity.val(data.ItemCount);
                        updateTotal(data, productId);
                        getMiniCart();
                    });
                }
            });

            function updateTotal(data, productId) {
                $('.cart-total').text(numberWithDots(data.CartTotal) + ' ₫');
                $('#product-subtotal-' + productId).text(numberWithDots(data.ItemTotal) + ' ₫');
            }
        });
    </script>
}

Views/ShoppingCart/_Checkout.cshtml
@model GardenShopOnline.Models.ShoppingCartViewModels

<div class="your-order-table table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th class="cart-product-name">Product</th>
                <th class="cart-product-total">Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.CartItems)
            {
                <tr class="cart_item">
                    <td class="cart-product-name">
                        @item.Product.Name<strong class="product-quantity">
                            × @item.Count
                        </strong>
                    </td>
                    <td class="cart-product-total"><span class="amount">@item.Subtotal.ToString("N0") ₫</span></td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr class="cart-subtotal">
                <th>Cart Subtotal</th>
                <td><span class="amount">@Model.CartTotal.ToString("N0") ₫</span></td>
            </tr>
            <tr class="order-total">
                <th>Order Total</th>
                <td><strong><span class="amount">@Model.CartTotal.ToString("N0") ₫</span></strong></td>
            </tr>
        </tfoot>
    </table>
    <input type="hidden" id="Total" name="Total" value="@Model.CartTotal" />
</div>

Views/ShoppingCart/_MiniCart.cshtml
@model GardenShopOnline.Models.ShoppingCartViewModels

<ul class="minicart-list">
    @foreach (var item in Model.CartItems)
    {
        <li class="minicart-product" id="miniRow-@item.RecordID">
            <a class="product-item_remove" href="#" data-id="@item.RecordID">
                <i class="pe-7s-close" data-tippy="Remove"
                   data-tippy-inertia="true" data-tippy-animation="shift-away" data-tippy-delay="50"
                   data-tippy-arrow="true" data-tippy-theme="sharpborder"></i>
            </a>
            <a href="single-product-variable.html" class="product-item_img">
                <img class="img-full" src="~/assets/images/@item.Product.Image" alt="Product Image">
            </a>
            <div class="product-item_content">
                <a class="product-item_title" href="single-product-variable.html">@item.Product.Name</a>
                <span class="product-item_quantity">@item.Count x @item.Product.Price.ToString("N0") ₫</span>
            </div>
        </li>
    }
</ul>

<div class="minicart-item_total">
    <span>Subtotal</span>
    <span class="ammount">@Model.CartTotal.ToString("N0") ₫</span>
</div>
<div class="group-btn_wrap d-grid gap-2">
    <a href="@Url.Action("Index", "ShoppingCart")" class="btn btn-dark">View Cart</a>
    <a href="@Url.Action("AddressAndPayment", "Checkout")" class="btn btn-dark">Checkout</a>
</div>