Models/Category.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}

Controllers/CategoriesController.cs
using GardenShopOnline.Models;
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace GardenShopOnline.Controllers
{
    [CustomAuthorize(Roles = "Admin, Staff")]
    public class CategoriesController : Controller
    {
        private readonly BonsaiGardenEntities db = new BonsaiGardenEntities();

        // GET: Categories
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult _CategoryList()
        {
            var categories = db.Categories.Where(c => c.Status != 3).OrderByDescending(c => c.ID);

            return PartialView(categories.ToList());
        }
        public JsonResult Create_Category(string name_category)
        {
            string message = "";
            bool status = true;
            try
            {
                int check = db.Categories.Where(c => c.Name == name_category).Count();
                if (check > 0)
                {
                    status = false;
                    message = "Category name already exists";
                }
                else
                {
                    Category Category = new Category
                    {
                        Name = name_category,
                        Status = 1
                    };
                    db.Categories.Add(Category);
                    db.SaveChanges();
                    message = "Created successfully";
                    status = true;
                }

            }
            catch (Exception e)
            {
                status = false;
                message = e.Message;
            }

            return Json(new { status, message }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult EditStatus_Category(Category Categorys)
        {
            Category categories = db.Categories.Find(Categorys.ID);
            if (categories.Status == 1)
            {
                categories.Status = 2;
            }
            else
            {
                categories.Status = 1;
            }
            db.Entry(categories).State = EntityState.Modified;
            db.SaveChanges();
            return Json("EditStatus_Category", JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult FindCategory(int Category_id)
        {

            Category categories = db.Categories.Find(Category_id);
            var emp = new Category
            {
                ID = Category_id,
                Name = categories.Name
            };
            return Json(emp);
        }
        public JsonResult UpdateCategory(int category_id, string name_category)
        {
            string message = "";
            bool status = true;
            try
            {
                int check = db.Categories.Where(c => c.Name == name_category).Count();
                if (check > 0)
                {
                    status = false;
                    message = "Category name already exists";
                }
                else
                {
                    Category categories = db.Categories.Find(category_id);
                    categories.Name = name_category;
                    db.Entry(categories).State = EntityState.Modified;
                    db.SaveChanges();
                    message = "Record Saved Successfully ";
                    status = true;
                }
            }
            catch (Exception e)
            {
                status = false;
                message = e.Message;
            }


            return Json(new { status, message }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Delete_Category(Category categorys)
        {
            bool status = true; try
            {
                Category categories = db.Categories.Find(categorys.ID);
                db.Categories.Remove(categories);
                db.SaveChanges();
            }
            catch
            {
                status = false;
            }

            return Json(new { status = status }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getCategory()
        {

            return Json(db.Categories.Where(c => c.Status == 1).OrderByDescending(c => c.ID).Select(x => new
            {
                categoryID = x.ID,
                categoryName = x.Name
            }).ToList(), JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Categories/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

}
<input type="text" hidden id="URL_List" value="@Url.Action("_CategoryList", "categories")" />
<input type="text" hidden id="URLFindCategory" value="@Url.Action("FindCategory", "categories")/" />

<section class="pcoded-main-container">
    <div class="pcoded-content">
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Category</h5>
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="https://tancool.net">
                                    <i class="feather icon-home">
                                    </i>
                                </a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="javascript:void(0)">Category</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-md-10">
                                    <h4>CATEGORY</h4>
                                </div>
                                <div class="col-md-2">
                                    <button type="button" class="btn  btn-primary btn-block" data-toggle="modal" data-target="#Addform">Add new</button>
                                </div>
                            </div>
                        </div>
                        <div class="card-body table-border-style">
                            <div class="table-responsive" id="dataContainer">
                                @{ Html.RenderAction("_CategoryList", "Categories");}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div id="Addform" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="AddCategoryLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form class="needs-validation CGForm" method="post" action="@Url.Action("Create_Category", "categories")" novalidate>
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    <h5 class="modal-title" id="AddCategoryLabel">>Add new Category</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>

                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>
                                    Category name<span class="text-danger">*</span>
                                </label>
                                <div class="position-relative">
                                    <input type="text" placeholder="Category name..." id="Add_name" class="form-control" name="name_category" pattern="\S+.*" required>
                                    <div class="invalid-feedback">
                                        Please enter category name !
                                    </div>
                                </div> <!---->
                            </div>
                        </div>
                    </div>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn  btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div id="Edit_Modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="Edit_ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form class="needs-validation CGForm" method="post" action="@Url.Action("UpdateCategory", "categories")" novalidate>
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    <h5 class="modal-title" id="Edit_ModalLabel">Edit category</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>

                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>
                                    Category name<span class="text-danger">*</span>
                                </label>
                                <div class="position-relative">
                                    <input hidden id="edit_id" name="category_id" />
                                    <input type="text" placeholder="Category name..." id="Edit_name" class="form-control" name="name_category" pattern="\S+.*" required>
                                    <div class="invalid-feedback">
                                        Please enter category name !
                                    </div>
                                </div> <!---->
                            </div>
                        </div>
                    </div>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn  btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        var row;
        $(document).ready(function () {
            $('#example').DataTable({
                pagingType: 'full_numbers',
            });
        });
    </script>
}

Views/Categories/_CategoryList.cshtml
@model IEnumerable<GardenShopOnline.Models.Category>
@{ 
    int no = 0;
}
<table id="example" class="table table-hover">
    <thead>
        <tr>
            <th>#</th>

            <th class="text-center">Name</th>
            <th width="15%">Status</th>
            <th width="15%">
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            string customswitch_DM = "customswitch" + item.ID;
            no++;
            <tr>
                <td>@no <input hidden type="text" name="record" value="@item.ID"></td>

                <td class="text-center">@item.Name</td>

                <td>
                    @if (item.Status == 1)
                    {
                        <div class="custom-control custom-switch">
                            <input type="checkbox" checked class="custom-control-input" id="@customswitch_DM">
                            <label class="custom-control-label" for="@customswitch_DM"></label>
                        </div>
                    }
                    else
                    {
                        <div class="custom-control custom-switch">
                            <input type="checkbox" class="custom-control-input" id="@customswitch_DM">
                            <label class="custom-control-label" for="@customswitch_DM"></label>
                        </div>
                    }
                    <input hidden type="text" id="URDEditStatus" value="@Url.Action("EditStatus_Category", "categories")">
                    <script language="javascript">
                                                        document.getElementById('@customswitch_DM').onclick = function (e) {
                                                                EditStatus(@item.ID);
                                                        };
                    </script>
                </td>
                <td>
                    <button class="btn btn-success " onclick="GetCategory(this, @item.ID)">
                        <i class="feather icon-edit">
                        </i>
                    </button>
                    <input hidden type="text" id="URLDelete" value="@Url.Action("Delete_Category", "categories")">
                    <button class="btn btn-danger" onclick="deleteAlert('@item.ID', '@item.ID')" id="Delete">
                        <i class="feather icon-trash-2">
                        </i>
                    </button>

                </td>
            </tr>

        }

    </tbody>
</table>