Models/Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Carts = new HashSet<Cart>();
            this.CommentProducts = new HashSet<CommentProduct>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public int TypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<int> Status { get; set; }
        public int Quantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentProduct> CommentProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Type Type { get; set; }
    }
}

Controllers/ProductsController.cs
using GardenShopOnline.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GardenShopOnline.Controllers
{
    public class ProductsController : Controller
    {
        private readonly BonsaiGardenEntities db = new BonsaiGardenEntities();

        // GET: Products
        [CustomAuthorize(Roles = "Admin, Staff")]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetRelatedProducts(int productId, int typeId, int categoryId)
        {
            // Get related products list based on type and category
            return PartialView("_RelatedProducts", db.Products.Where(p => p.ID != productId && p.Status == 1 && (p.TypeID == typeId || p.CategoryID == categoryId)).ToList());
        }

        [CustomAuthorize(Roles = "Admin, Staff")]
        // sử dụng PartialView để có thể lọc sản phẩm mà không load lại toàn trang
        public ActionResult ProductList(int category_id, int type_id)
        {
            var links = from l in db.Products
                        where l.Category.Status != 3 && l.Type.Status != 3
                        select l;

            if (category_id != -1)
            {
                links = links.Where(p => p.CategoryID == category_id);
            }
            if (type_id != -1)
            {
                links = links.Where(p => p.TypeID == type_id);
            }
            return PartialView(links.Where(c => c.Status != 3).OrderByDescending(c => c.ID));

        }
        [HttpPost]
        [ValidateInput(false)]
        [CustomAuthorize(Roles = "Admin, Staff")]

        public ActionResult Create_Product(string name_product,
           int quantity, int CategoryDropdown, int TypeDropdown,
           string price, string description, HttpPostedFileBase file)
        {
            Product product = new Product();

            product.Name = name_product;
            product.Quantity = quantity;
            product.CategoryID = CategoryDropdown;
            product.TypeID = TypeDropdown;
            product.Price = int.Parse(price.Replace(",", ""));
            product.Description = description;
            product.Status = 1;
            string filename = Path.GetFileName(file.FileName);
            string _filename = DateTime.Now.ToString("yymmssfff") + filename;

            string extension = Path.GetExtension(file.FileName);

            string path = Path.Combine(Server.MapPath("~/assets/images/"), _filename);

            product.Image = _filename;
            if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
            {
                if (file.ContentLength <= 4000000)
                {
                    db.Products.Add(product);

                    if (db.SaveChanges() > 0)
                    {
                        file.SaveAs(path);

                    }
                }
                else
                {
                    ViewBag.msg = "Hình ảnh phải lớn hơn hoặc bằng 4MB!";
                }
            }
            else
            {
                ViewBag.msg = "Định dạng file không hợp lệ!";
            }
            db.SaveChanges();
            Session["notification"] = "Thêm mới thành công!";
            return RedirectToAction("Index");
        }
        [CustomAuthorize(Roles = "Admin, Staff")]
        public ActionResult Delete_Product(Product product)
        {
            bool status = true; 
            try
            {
                Product product1 = db.Products.Find(product.ID);
                db.Products.Remove(product1);
                db.SaveChanges();
            }
            catch
            {
                status = false;
            }

            return Json(new { status = status }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        [CustomAuthorize(Roles = "Admin, Staff")]
        public JsonResult FindProduct(int Product_id)
        {
            Product product = db.Products.Find(Product_id);
            var emp = new Product();
            emp.ID = Product_id;
            emp.Name = product.Name;
            emp.Quantity = product.Quantity;
            emp.Price = product.Price;
            emp.CategoryID = product.CategoryID;
            emp.Image = product.Image;
            emp.Description = product.Description;
            return Json(emp);
        }
        [HttpPost]
        [ValidateInput(false)]
        [CustomAuthorize(Roles = "Admin, Staff")]
        public ActionResult UpdateProduct(int Product_id, string name_product,
           int quantity, int CategoryDropdown, int TypeDropdown,
           string price, string description, HttpPostedFileBase file)
        {
            Product product = db.Products.Find(Product_id);
            Session["imgPath"] = product.Image;
            product.Name = name_product;
            product.CategoryID = CategoryDropdown;
            product.TypeID = TypeDropdown;
            product.Price = int.Parse(price.Contains('.') ? price.Replace(".", "") : price.Replace(",", ""));
            product.Quantity = quantity;
            product.Description = description;
            product.DateUpdate = DateTime.Now;

            if (file != null)
            {
                string filename = Path.GetFileName(file.FileName);
                string _filename = DateTime.Now.ToString("yymmssfff") + filename;

                string extension = Path.GetExtension(file.FileName);

                string path = Path.Combine(Server.MapPath("~/assets/images/"), _filename);

                product.Image = _filename;

                if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
                {
                    if (file.ContentLength <= 4000000)
                    {
                        db.Entry(product).State = EntityState.Modified;
                        string oldImgPath = Request.MapPath(Session["imgPath"].ToString());

                        if (db.SaveChanges() > 0)
                        {
                            file.SaveAs(path);
                            if (System.IO.File.Exists(oldImgPath))
                            {
                                System.IO.File.Delete(oldImgPath);
                            }
                            return RedirectToAction("Index");
                        }
                    }
                    else
                    {
                        ViewBag.msg = "Hình ảnh phải lớn hơn hoặc bằng 4MB!";
                    }
                }
                else
                {
                    ViewBag.msg = "Định dạng file không hợp lệ!";
                }
            }
            else
            {
                product.Image = Session["imgPath"].ToString();
            }

            db.Entry(product).State = EntityState.Modified;
            db.SaveChanges();
            Session["notification"] = "Cập nhật thành công!";
            return RedirectToAction("Index");
        }

        // GET: Products1/Create
        [CustomAuthorize(Roles = "Admin, Staff")]
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name");
            return View();
        }

        // GET: Products1/Edit/5
        [CustomAuthorize(Roles = "Admin, Staff")]
        public ActionResult Edit(int id)
        {
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", product.CategoryID);
            return View(product);
        }

        // GET: Products/Details
        public ActionResult Details(int id)
        {
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewData["CommentCount"] = db.CommentProducts.Where(c => c.ProductID == id && c.Status == 2).Count();
            return View(product);
        }

        [CustomAuthorize(Roles = "Admin, Staff")]
        public ActionResult Comment_product(int product_id, string content)
        {
            CommentProduct comment = new CommentProduct();
            comment.Content = content;
            comment.ProductID = product_id;
            comment.DateCreated = DateTime.Now;
            comment.UserID = User.Identity.GetUserId();
            comment.Status = 1;
            db.CommentProducts.Add(comment);
            db.SaveChanges();
            return Json("Comment_product", JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Products/Create.cshtml
@model GardenShopOnline.Models.Product

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<input type="text" hidden id="URLgetCategory" value="@Url.Action("getCategory", "Categories")" />
<input type="text" hidden id="URLgetType" value="@Url.Action("getType", "Types")" />

<section class="pcoded-main-container">
    <div class="pcoded-content">
        <!-- [ breadcrumb ] start -->
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Product Management</h5>
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html"><i class="feather icon-home"></i></a></li>
                            <li class="breadcrumb-item"><a href="#!">Products</a></li>
                            <li class="breadcrumb-item"><a href="#!">Create Product</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ breadcrumb ] end -->
        <!-- [ Main Content ] start -->
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5>Create product</h5>
                    </div>
                    <div class="card-body">
                        <form class="needs-validation" method="post" action="@Url.Action("Create_Product", "products")" enctype="multipart/form-data" novalidate>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>
                                            Name <span class="text-danger">*</span>
                                        </label>
                                        <div class="position-relative">
                                            <input type="text" placeholder="Enter product name..." id="add_name" class="form-control" name="name_product" pattern="\S+.*" required>
                                            <div class="invalid-feedback">
                                                Please enter product name !
                                            </div>
                                        </div> <!---->
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>
                                            Category <span class="text-danger">*</span>
                                        </label>
                                        <div class="position-relative">
                                            <select class="custom-select" id="CategoryDropdown" name="CategoryDropdown" required>
                                            </select>
                                            <div class="invalid-feedback">Please select product category !</div>
                                        </div> <!---->

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>
                                            Type <span class="text-danger">*</span>
                                        </label>
                                        <div class="position-relative">
                                            <select class="custom-select" id="TypeDropdown" name="TypeDropdown" required>
                                            </select>
                                            <div class="invalid-feedback">Please select product type !</div>
                                        </div> <!---->

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>
                                            Quantity <span class="text-danger">*</span>
                                        </label>
                                        <div class="position-relative">
                                            <input type="text" placeholder="Enter product quantity... " id="add_quantity" class="form-control " name="quantity" pattern="\S+.*" required>
                                            <div class="invalid-feedback">
                                                Please enter product quantity !
                                            </div>
                                        </div> <!---->
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>
                                            Price <span class="text-danger">*</span>
                                        </label>
                                        <div class="position-relative">
                                            <input type="text" placeholder="Enter product price..." id="product-price" max="999999999999" class="form-control "
                                                   pattern="[0-9.,]+" data-type="number" name="price" required>
                                            <div class="invalid-feedback">
                                                Product price cannot be blank !
                                            </div>
                                        </div> <!---->

                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Description</label>
                                        <div class="position-relative">
                                            <textarea id="description" name="description" placeholder="Enter product description..." rows="4" class="form-control"></textarea>
                                        </div>
                                        <!---->
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>
                                            Image <span class="text-danger">(*)</span>
                                        </label>
                                        <div class="position-relative">
                                            <div class="img-item">
                                                <img id="output" class="img-item-link" />

                                            </div>
                                            <input type="file" required="required" name="file" id="file" class="form-control" accept="image/x-png,image/gif,image/jpeg" onchange="loadFile_edit(event)" />
                                            <div class="invalid-feedback">
                                                Please choose an image for the product!
                                            </div>
                                        </div>
                                        <script>
                                            var loadFile_edit = function (event) {
                                                var image = document.getElementById('output');
                                                image.src = URL.createObjectURL(event.target.files[0]);
                                            };
                                        </script>
                                    </div>
                                </div>


                                <div class="col-md-12 ">
                                    <button type="submit" class="btn btn-primary float-right">Save</button>

                                    <button type="button" class="btn  btn-secondary float-right" onclick="location.href='@Url.Action("Index","Products")';">Cancel</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
        <!-- [ Main Content ] end -->

    </div>
</section>






<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Products/Edit.cshtml
@model GardenShopOnline.Models.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<input type="text" hidden id="URLgetCategory" value="@Url.Action("getCategory", "Categories")" />
<input type="text" hidden id="PEdit_Description" value="@Model.Description" />
<input type="text" hidden id="URLgetType" value="@Url.Action("getType", "Types")" />

<section class="pcoded-main-container">
    <div class="pcoded-content">
        <!-- [ breadcrumb ] start -->
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Product Management</h5>
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html"><i class="feather icon-home"></i></a></li>
                            <li class="breadcrumb-item"><a href="#!">Products</a></li>
                            <li class="breadcrumb-item"><a href="#!">Edit Product</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ breadcrumb ] end -->
        <!-- [ Main Content ] start -->
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5>Ccreate product</h5>
                    </div>
                    <div class="card-body">
                        <form class="needs-validation" method="post" action="@Url.Action("UpdateProduct", "products")" enctype="multipart/form-data" novalidate>
                            <input hidden id="edit_id" name="Product_id" value="@Model.ID" />
                            <input hidden id="edit_Category_id" value="@Model.CategoryID" />
                            <input hidden id="edit_Type_id" value="@Model.TypeID" />

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>
                                            Name <span class="text-danger">*</span>
                                        </label>
                                        <div class="position-relative">
                                            <input type="text" placeholder="Enter product name..." id="add_name" class="form-control" value="@Model.Name" name="name_product" pattern="\S+.*" required>
                                            <div class="invalid-feedback">
                                                Please enter product name !
                                            </div>
                                        </div> <!---->
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>
                                            Category <span class="text-danger">*</span>
                                        </label>
                                        <div class="position-relative">
                                            <select class="custom-select" id="CategoryDropdown" name="CategoryDropdown" required>
                                            </select>
                                            <div class="invalid-feedback">Please select product category !</div>
                                        </div> <!---->

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>
                                            Category <span class="text-danger">*</span>
                                        </label>
                                        <div class="position-relative">
                                            <select class="custom-select" id="TypeDropdown" name="TypeDropdown" required>
                                            </select>
                                            <div class="invalid-feedback">Please select product category !</div>
                                        </div> <!---->

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>
                                            Quantity <span class="text-danger">*</span>
                                        </label>
                                        <div class="position-relative">
                                            <input type="text" placeholder="Enter product quantity... " value="@Model.Quantity" id="add_quantity" class="form-control " name="quantity" pattern="\S+.*" required>
                                            <div class="invalid-feedback">
                                                Please enter product quantity !
                                            </div>
                                        </div> <!---->
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>
                                            Price <span class="text-danger">*</span>
                                        </label>
                                        <div class="position-relative">
                                            <input type="text" placeholder="Enter product price..." value="@Model.Price.ToString("N0")" id="product-price" max="999999999999" class="form-control "
                                                   pattern="[0-9.,]+" data-type="number" name="price" required>
                                            <div class="invalid-feedback">
                                                Product price cannot be blank !
                                            </div>
                                        </div> <!---->

                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Description</label>
                                        <div class="position-relative">
                                            <textarea id="description" name="description" placeholder="Enter product description..." rows="4" class="form-control"></textarea>
                                        </div>
                                        <!---->
                                    </div>
                                </div>
                                <script>

                                </script>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>
                                            Image <span class="text-danger">(*)</span>
                                        </label>
                                        <div class="position-relative">
                                            <div class="img-item">
                                                <img id="output" class="img-item-link" src="@Url.Content("~/assets/images/" +Model.Image)" />

                                            </div>
                                            <input type="file" name="file" id="file" class="form-control" accept="image/x-png,image/gif,image/jpeg" onchange="loadFile_edit(event)" />
                                            <div class="invalid-feedback">
                                                Please choose an image for the product!
                                            </div>
                                        </div>
                                        <script>
                                            var loadFile_edit = function (event) {
                                                var image = document.getElementById('output');
                                                image.src = URL.createObjectURL(event.target.files[0]);
                                            };
                                        </script>
                                    </div>
                                </div>


                                <div class="col-md-12 ">
                                    <button type="submit" class="btn btn-primary float-right">Save</button>

                                    <button type="button" class="btn  btn-secondary float-right" onclick="location.href='@Url.Action("Index","Products")';">Cancel</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
        <!-- [ Main Content ] end -->

    </div>
</section>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Products/_RelatedProducts.cshtml
@model IEnumerable<GardenShopOnline.Models.Product>

@foreach (var item in Model)
{
    <div class="swiper-slide product-item">
        <div class="product-img">
            <a href="@Url.Action("Details", "Products", new { id = item.ID })">
                <img class="primary-img" src="~/assets/images/@item.Image" alt="Product Images">
            </a>
            <div class="product-add-action">
                <ul>
                    <li>
                        <a class="add-to-cart" href="@Url.Action("AddToCart", "ShoppingCart", new { id = item.ID })" data-tippy="Add to cart" data-tippy-inertia="true" data-tippy-animation="shift-away" data-tippy-delay="50" data-tippy-arrow="true" data-tippy-theme="sharpborder">
                            <i class="pe-7s-cart"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="product-content">
            <a class="product-name" href="single-product-variable.html">@item.Name</a>
            <div class="price-box pb-1">
                <span class="new-price">@item.Price.ToString("N0") ₫</span>
            </div>
        </div>
    </div>
}